### ISSUE TITLE
utime() fails to assign current time to file

### ISSUE THREAD

**Issue by vamsikrishna935** [lsds/sgx-lkl#157]
Utime03 is failing because of this issue. Please find the testcase details below.
https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/syscalls/utime/utime03.c

utime syscall : http://man7.org/linux/man-pages/man2/utime.2.html

Analysis :
Temporary file is created while setup and test tries to test utime syscall.
TEST(utime(TEMP_FILE, NULL)); This will call utime on temp_file and changes modified and access times to current time (Expected Behavior of utime syscall)
But in actual it is not setting it to current time , because the system time is  00:00:00 UTC on 1 January 1970. Here are some findings.
TEST(utime(TEMP_FILE, NULL)) will return -1 on failure.
1. Verification step.
    - In the test we are  capturing the time stamps before (in the variable curr_time) and after (in the variable pres_time) calling utime to perform validation.
    - We do have sleep for few seconds to get difference in times
    - So we call utime() on temp file , both modifed & access times of files should be greater than curr_time (captured before utime using time() function) and less than pres_time

2. Actual behavior TEST(utime(TEMP_FILE, NULL))    
    - TEST(utime(TEMP_FILE, NULL)) got succeeded.
    - Below are the debugging details
    - (gdb) p access_time
    $1 = 64
    (gdb) p modf_time
    $2 = 64
    (gdb) p user_uid
    $3 = 0
    (gdb) p curr_time
    $4 = 1587997633
    (gdb) p pres_time
    $5 = 1587997644
    (gdb) p stat_buf
    $6 = {st_dev = 65024, st_ino = 169, st_nlink = 1, st_mode = 33270, st_uid = 1, st_gid = 1, __pad0 = 0, st_rdev = 0,
  st_size = 0, st_blksize = 4096, st_blocks = 0, st_atim = {tv_sec = 64, tv_nsec = 120000000}, st_mtim = {tv_sec = 64,
    tv_nsec = 120000000}, st_ctim = {tv_sec = 64, tv_nsec = 120000000}, __unused = {140734238814168, 140734279192000,
    140733199559282}}
    - It didn't set the file modified & access times to current which is not expected.

**Comment by vamsikrishna935** [comment]
https://github.com/lsds/sgx-lkl/issues/121 is not fixed , cannot able to reopen the issue 121 . So created a new issue to track it.

**Comment by SeanTAllen** [comment]
This is definitely broken on oe_port and would have been for a while from the looks of it. utime03 and a couple more of the utime tests pass on my ongoing in-enclave-time-source branch. However, at the moment, that branch is breaking a couple of other things.  

I'm trying to see if I can get a slightly abbreviated version of the "in-enclave time source" work to pass CI that would include the utime fixes which would, in theory, be mergeable before all the work is done.

**Comment by SeanTAllen** [comment]
This is fixed as part of https://github.com/lsds/sgx-lkl/issues/134 work.

I'll update this issue when those changes are merged.

**Comment by SeanTAllen** [comment]
This has been addressed. The utime03 ltp test is now on as part of the changes and will run for CI for everything going forward.

https://github.com/lsds/sgx-lkl/commit/5bb8a20a9567e7c2a77bf64957201704a3ca0545

**Comment by SeanTAllen** [comment]
@vamsikrishna935 @hukoyu you are good to go.

**Comment by vamsikrishna935** [comment]
> 
> 
> @vamsikrishna935 @hukoyu you are good to go.

@SeanTAllen , Verified in latest code in oe_port branch, issue still presents. Please find debugging details below.
(gdb) p modf_time
$3 = 64
(gdb) p access_time
$4 = 64
(gdb) p stat_buf
$5 = {st_dev = 11, st_ino = 612, st_nlink = 1, st_mode = 33270, st_uid = 1, st_gid = 1, __pad0 = 0, st_rdev = 0,
  st_size = 0, st_blksize = 4096, st_blocks = 0, st_atim = {tv_sec = 64, tv_nsec = 920000000}, st_mtim = {tv_sec = 64,
    tv_nsec = 920000000}, st_ctim = {tv_sec = 64, tv_nsec = 920000000}, __unused = {140734279159656, 140734279151040,
    140733199524115}}

**Comment by SeanTAllen** [comment]
@vamsikrishna935 are you saying that the ltp utime03 test doesn't pass for you? It passes for me both locally and it passes CI.

**Comment by vamsikrishna935** [comment]
> 
> 
> @vamsikrishna935 are you saying that the ltp utime03 test doesn't pass for you? It passes for me both locally and it passes CI.

Yes utime03 is failing for me. Just verified with latest code in oe_port branch. 
[[  SGX-LKL ]] libc_start_main_stage2(): Calling app main: /ltp/testcases/kernel/syscalls/utime/utime03
utime03     1  TFAIL  :  utime03.c:196: tmp_file access and modification times not set

**Comment by SeanTAllen** [comment]
@vamsikrishna935 can you describe how you are building everything and your environment as it passes in CI on oe_port and locally for me.

**Comment by SeanTAllen** [comment]
@vamsikrishna935 here is how I am testing locally:

```
git clone git@github.com:lsds/sgx-lkl.git
cd sgx-lkl/
git checkout oe_port
make DEBUG=true
cd tests/ltp/ltp-batch1/
```

then editing ../batch.mk to run off run-hw and run-sw running all tests so i can run one test followed by

```
make clean && make DEBUG=true && make run
SGXLKL_VERBOSE=1 SGXLKL_KERNEL_VERBOSE=0 ../../../build/sgx-lkl-run-oe --hw-debug  sgxlkl-miniroot-fs.img /ltp/testcases/kernel/syscalls/utime/utime03
```

I'm able to run the last command that runs the test repeatedly without any failures. I just ran it 10 times in a row without issue.

Each time I get:

```
utime03     1  TPASS  :  Functionality of utime(tmp_file, NULL) successful
```

**Comment by vamsikrishna935** [comment]
@SeanTAllen Let me verify with clean repo again and i will update you the status.

**Comment by hukoyu** [comment]
@SeanTAllen are you using oe_port branch of sgx-lkl? In your steps you are not checking out oe_port branch, can you double check?

**Comment by SeanTAllen** [comment]
Sorry, yes, I left that out. I am using that port. I will update the steps, my oversight in writing them up. Sorry for the confusion @hukoyu @vamsikrishna935.

**Comment by hukoyu** [comment]
@SeanTAllen  I checked utime03 and actually it is timing out and since we were not checking exit code, it was hiding timeouted tests. I submitted this PR : https://github.com/lsds/sgx-lkl/pull/220
utime03 is also failing in this PR. Per @letmaik  's recommendtaion I will disable utime03 test for now until we understand why it is failing.

**Comment by SeanTAllen** [comment]
@hukoyu it times out for you locally?

**Comment by vamsikrishna935** [comment]
@hukoyu : for me it is failing , i did not get any time out till now for utime03

**Comment by hukoyu** [comment]
@SeanTAllen it is failed in CI pipeline. Check this: https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=224&view=logs&j=0d1659af-9dce-5414-770d-ef96fb05931d&t=81d6e709-66cb-5bbd-8ebe-3e7ad763e195

**Comment by hukoyu** [comment]
@SeanTAllen  @vamsikrishna935  I disabled utime03 test in my PR for now. FYI
PR : #220

**Comment by hukoyu** [comment]
@SeanTAllen @vamsikrishna935  I got confused between utime03 and times03. I disabled test times03 in my PR not utime03. times03 is timing out after 5 minutes. I enabled back utime03. @vamsikrishna935 please investigate times03 for timeout. Issue with utime03 is not time out issue, it must be something else.

**Comment by SeanTAllen** [comment]
@vamsikrishna935 I am unable in any environment to produce utime03 failing. If you can provide information on how I can do that, I'd appreciate it. All I get it passing results.

**Comment by SeanTAllen** [comment]
@hukoyu your times03 problem is probably related to #209.

**Comment by vamsikrishna935** [comment]
@SeanTAllen , Verified in latest repo today, the test is passing.
[[  SGX-LKL ]] libc_start_main_stage2(): Calling app main: /ltp/testcases/kernel/syscalls/utime/utime03
utime03     1  TPASS  :  Functionality of utime(tmp_file, NULL) successful
